#!/bin/sh

ln -s `pwd`/.vimrc ~/.vimrc
ln -s `pwd`/.tmux.conf ~/.tmux.conf

# create .vim directories
mkdir -p ~/.vim/colors
mkdir -p ~/.vim/autoload

# download solarized theme
wget -O ~/.vim/colors/solarized.vim https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim

# download linux kerned dev plugin
wget -O ~/.vim/autoload/linuxsty.vim https://raw.githubusercontent.com/vim-scripts/linuxsty.vim/master/indent/linuxsty.vim
